### ISSUE TITLE
Error running vrust docker

### ISSUE THREAD

**Issue by shinmao** [parasol-aser/vrust-open-source#2]
Hi, here I tried to run the docker of vrust but ran into some issues. After I built up the docker image, I tried to use `docker run -it -d <image_name>`; however, it ran into the following issue:
```
python3.9: can't open file '/vrust/rwp/run.py': [Errno 2] No such file or directory
```
This error causes to failure while starting up container.

**Comment by jncsw** [comment]
Hi, Rafael @shinmao!

Thank you for your interest in VRust! I have updated a patch for the Dockerfile entrypoint, and now it should be able to work directly out of the box. Also, you may override the default entrypoint with:

`sudo docker run -it --entrypoint /bin/bash <IMG_ID>`

Documentations for Docker support can be found [here](https://github.com/parasol-aser/vrust-open-source/blob/main/examples/README.md).

**Comment by shinmao** [comment]
@jncsw thanks for the response. I successfully run up the container. Now I tried to use vrust to scan the other targets directory (other from the ones in `examples/`). Following the documentation, I am not able to find `run.sh` in the container.

**Comment by jncsw** [comment]
Hi, @shinmao ,
You may want to look into this [python script](https://github.com/parasol-aser/vrust-open-source/blob/main/examples/run.py). You can use our updated Python script to analyze other targets:

`python3 /vrust/examples/run.py -v /PATH_TO_VRUST/target/debug/vrust -o /PATH_TO_VRUST/SmartV_Report_Generator \
 -s /PATH_TO_PROJECTS/metaplex-program-library -c mpl-metaplex -r /PATH_TO_REPORTS`

One example is under our docker entrypoint:
`python3.9 /vrust/examples/run.py -v /vrust/target/debug/vrust -o ./SmartV_Report_Generator/`

**Comment by shinmao** [comment]
I tried to run the first script on other project such as [Astar](https://github.com/AstarNetwork/Astar) and got the following failure
```
Caused by:
  invalid type: map, expected a sequence for key `package.authors`
error: failed to parse manifest at `/cess/hm2/targets/Astar/runtime/shibuya/Cargo.toml`
```
I am guessing the reason is that the checkers could only be used on targets of Solana, is it correct?

**Comment by jncsw** [comment]
Our implementation is targeting Solana Blockchain. It can be extended to support other platforms.

**Comment by shinmao** [comment]
Gotcha, so I might need to customize the implementation to support other targets.
